"""empty message

Revision ID: 490bd1f7efb5
Revises: 
Create Date: 2021-09-30 17:36:12.333464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '490bd1f7efb5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sharelink',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=True),
    sa.Column('gas', sa.Integer(), nullable=True),
    sa.Column('solve', sa.Integer(), nullable=True),
    sa.Column('hash', sa.String(length=6), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sharelink')
    # ### end Alembic commands ###
