"""empty message

Revision ID: 9336044ae156
Revises: 12dc11cd5456
Create Date: 2024-05-15 18:09:50.599458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9336044ae156'
down_revision = '12dc11cd5456'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sharelink', schema=None) as batch_op:
        batch_op.alter_column('depth',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('gas',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('solve',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('hash',
               existing_type=sa.VARCHAR(length=6),
               nullable=False)
        batch_op.alter_column('created',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.create_index(batch_op.f('ix_sharelink_created'), ['created'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sharelink', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sharelink_created'))
        batch_op.alter_column('created',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('hash',
               existing_type=sa.VARCHAR(length=6),
               nullable=True)
        batch_op.alter_column('solve',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('gas',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('depth',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
